### GAME
gameName: "base"
gameDescription: ["Base configuration for","Everyhunt"]

### STARTUP
autoStartOnLoad: false
minimumPlayers: 0
minimumRunners: 0
playersCanMidjoin: true
autoAddToGame: true
clearInventory: false

### SHUTDOWN
removeCompasses: true

### TRACKING COMPASS
useBlacklist: true
blacklistMessage: "Tracking this entity is not allowed!"
compassBlacklist: []
compassWhitelist: ["player"]
rightClickCyclesRunners: false
rightClickResetsDeadCompass: true
guiEnabled: true

### PORTALS
disablePortals: false

### LOBBY


### ROLES
assignRolesAtStart: false
assignRoleAtMidjoin: "hunter"
playersCanChangeRole: true

### HUNTERS
assignTargetAtStart: true
huntersCanChangeTarget: true
huntersCanBeRunners: true
huntersCanTrackDeadTargets: true

### RUNNERS
nonRunnersCanBeTargeted: false
autoAddRunners: false
autoRemoveRunners: true