### GAME META
gameName: "base"

gameDescription: ["A classic game of","Minecraft Manhunt!"]

### DEBUGGER

debugMode: true

debugTag: "§d{DEBUG} "

### TRACKING COMPASS

useBlacklist: true

blacklistMessage: "Tracking this entity is not allowed!"

compassWhitelist: ["player"]

compassBlacklist: []

rightClickCyclesRunners: false

rightClickResetsDeadCompass: true

guiEnabled: true

### PORTALS

disablePortals: false

### ROLES

huntersCanBeRunners: true

nonRunnersCanBeTargeted: false

autoAddRunners: true

autoRemoveRunners: true