debug: true

gamemode: "classic"

description: ["A classic game of","Minecraft Manhunt!"]

### TRACKING COMPASS

useBlacklist: true

blacklistMessage: "Tracking this entity is not allowed!"

compassWhitelist: ["player"]

compassBlacklist: []

rightClickCyclesRunners: false

rightClickResetsDeadCompass: true

guiEnabled: true

### PORTALS

disablePortals: false

### ROLES

huntersCanBeRunners: true

nonRunnersCanBeTargeted: false